version: 1
disable_existing_loggers: false
formatters:
    default:
        format: '%(levelname)s : %(name)s : %(module)s : %(funcName)s : %(message)s'
    ecsformatter:
        class: ecs_logging.StdlibFormatter
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: ecsformatter
    access_file:
        class: logging.FileHandler
        formatter: ecsformatter
        filename: /tmp/uvicorn.recommendation.access.log
    error_file:
        class: logging.FileHandler
        formatter: ecsformatter
        filename: /tmp/uvicorn.recommendation.error.log
loggers:
    root:
        handlers: [console]
        level: DEBUG
    uvicorn.access:
        handlers: [access_file, console]
        level: INFO
        qualname: uvicorn.access
        propagate: false
    uvicorn.error:
        handlers: [error_file, console]
        level: INFO
        qualname: uvicorn.error
        propagate: false
    httpx:
        handlers': [console]
        level': INFO
        propagate: false
    httpcore:
        handlers': [console]
        level': INFO
        propagate: false
